language: python
python:
  - "3.6"
dist: xenial
before_install:
  - sudo apt-get update
  - sudo apt-get install -y sqlite3
  - pip3 install --upgrade pip
install:
  - pip3 install -r requirements.txt
script: python3 manage.py test