# Generated by Django 2.2.2 on 2019-07-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20190703_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='given_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='pub_year',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Publication Year'),
        ),
        migrations.AlterField(
            model_name='book',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
